### ISSUE TITLE
First search result contains colour codes

### ISSUE THREAD

**Issue by dagda1** [Wilfred/ag.el#105]
Recently my ag search results have started returning corrupted results like this:
`
[[?25h^[[0G^[[?25h^[[0Gapp/config/development.coffee:49:33:#`

I am not sure how this was introduced.  I have my init.el in github and I have tried checking out old versions but the problem remains.

Is there a way that I can stop this, perhaps by using ```ag-arguments```?

**Comment by Wilfred** [comment]
What platform are you on? What version of ag?

**Comment by kthelgason** [comment]
I have the same issue. On OS X, ag and emacs at latest version installed through homebrew.

**Comment by dagda1** [comment]
I am glad to know it is not just me.  I am using ag version ```20160321.1606``` on OSX EL Capitan ```10.11.4```.

**Comment by kthelgason** [comment]
I traced this down to some weirdness in my config. Not a problem with ag.el.

**Comment by dagda1** [comment]
@kthelgason  can you tell me what the shell config change was.  I think that might be the same one as me

**Comment by kthelgason** [comment]
@dagda1 In my case it seemed to be related to setting `NODE_PATH` as the output of `npm -g root`. Don't ask me how that makes any sense but removing that single line fixed the problem for me.
