### ISSUE TITLE
ag-ignore-list buffer local and editable

### ISSUE THREAD

**Issue by fommil** [Wilfred/ag.el#141]
Could you please include these lines?

```
  (make-variable-buffer-local 'ag-ignore-list)
  (put 'ag-ignore-list 'safe-local-variable #'listp)
```

This allows per-directory exclusions (something not supported by `ag` itself https://github.com/ggreer/the_silver_searcher/issues/1181)

**Comment by Wilfred** [comment]
Would you mind submitting a PR?
