### ISSUE TITLE
Keybinding to open result in other window

### ISSUE THREAD

**Issue by holocronweaver** [Wilfred/ag.el#142]
I have `ag-reuse-window` set to `t`, but I still sometimes want to open a result in another window.

Could we add a keybinding to open the result window in another window, regardless of the setting of `ag-reuse-window`? Maybe bind `o` for 'other window'.

**Comment by Wilfred** [comment]
You should be able to do this by binding `compile-goto-error` (which is the underlying function) directly in the mode map:

```emacs-lisp
(define-key ag-mode-map "o" #'compile-goto-error)
```

I think this is too specific to justify adding to ag.el proper, so I'm closing. I'm open to persuasion, of course :)

**Comment by holocronweaver** [comment]
Hm, I tried that and pressing `o` opened the result in the same window. Any idea why?
