### ISSUE TITLE
What is silversearcher-ag-el?

### ISSUE THREAD

**Issue by kkhan01** [Wilfred/ag.el#156]
This is not a bug or feature request. My google-fu has failed me, and so I'm asking here. What is silversearcher-ag-el? I'm using ubuntu, but I doubt that will matter. This package's description is
```
Description-en: Emacs frontend to ag
 The Silver Searcher (a.k.a. ag) is very fast grep-like program.
 It is faster and has an attractive features than grep.
 ag.el is simple ag frontend for Emacs, loosely based on ack-and-half.el.
```
and its home page is
```
Homepage: https://github.com/Wilfred/ag.el
```
What does it mean by frontend for emacs? How does it differ from silversearcher-ag? I've installed and tried both both without seeing any change?  I figured the el had something to do with emacs based off of elisp, but as evident by [this link](https://agel.readthedocs.io/en/latest/installation.html) one should install the ggreer binary and use the melpa package. What would one need to properly set up ag with emacs on a fresh install? What purpose does silversearcher-ag-el serve? (yes, I did make an similar issue in ggreer's, but I've decided that it may be better answered here). Sorry if I asked too many questions :pensive:

**Comment by Wilfred** [comment]
Ag.el is a frontend, which means it lets you use the `ag` command inside Emacs. The `ag` command does the hard work of doing the search.

"The silver searcher" is just another name for `ag`. You need both `ag` and a frontend like ag.el to use ag from Emacs on a fresh install.

I hope that helps! :)
