### ISSUE TITLE
Print total matches

### ISSUE THREAD

**Issue by priyadarshan** [Wilfred/ag.el#63]
Would it be possible to add total matches found (possibly, in how many total files)? It could be in the `*ag search*` buffer, or, if it wouldn't be compatible with other packages (like `wgrep`), just a message in the minibuffer would be all right, something like `1071 matches across 363 files`.

I find this feature quite useful, as it can give a quick ballpark idea if the search string was properly set, or not.

Thank you so much for `ag.el`, it is indispensable.

**Comment by kaushalmodi** [comment]
The `--stats` option prints a summary like below:

```
32 matches
9576 files searched
97088546 bytes searched
1.511894 seconds
```
You can enable that by adding the below to your emacs init file after `(require 'ag)`.

```el
(add-to-list 'ag-arguments "--stats") 
```

**Comment by Wilfred** [comment]
Aha, so `--stats` is now much more informative.

I'm going to add `--stats` to the default value of `ag-arguments`. v1.0 will make this prettier, but this is a definite improvement today.

**Comment by priyadarshan** [comment]
Thank you. Thanks for the good news about v1.0, too!
