### ISSUE TITLE
ag-mode does not play well with Meteor package name convention.

### ISSUE THREAD

**Issue by nomosyn** [Wilfred/ag.el#68]
Meteor package convention : 
`myname:mypackage/file.js`

That leads in compilation buffer to:
`myname:mypackage/file.js:12:43:`

Which is not recognized.

Ex:
![capture d ecran 2014-10-16 a 14 12 34](https://cloud.githubusercontent.com/assets/2693150/4662211/3608cf4c-552e-11e4-802a-b1967d959794.png)

What we would like:
![capture d ecran 2014-10-16 a 14 13 22](https://cloud.githubusercontent.com/assets/2693150/4662218/4e777fb0-552e-11e4-8059-2577ee5c6cb7.png)

**Comment by Wilfred** [comment]
Closing as v1.0 will use more robust output parsing anyway.
