### ISSUE TITLE
k key in ag

### ISSUE THREAD

**Issue by ghost** [Wilfred/ag.el#72]
hi there, thanks for the very nice plugin for ag. I'm very new to Emacs. I experience a strange behavior when using `k` to go up in ag buffer. It seems to switch to another buffer instead of go up, meanwhile `j` to go down works perfectly.
It'd be great if you do have any hint about this. 

Thanks

**Comment by Wilfred** [comment]
Hi folks

ag.el support has now been added to evil itself. If you update to the latest ag.el, you will need to upgrade to the latest evil version to avoid regressions.

As always, please file bugs if you see issues.
