### ISSUE TITLE
Won't byte-compile without evil installed

### ISSUE THREAD

**Issue by purcell** [Wilfred/ag.el#82]
When `evil` is not installed, then

```
(eval-after-load 'evil
  `(progn
     (eval-when-compile (require 'evil-core))
     (add-to-list 'evil-motion-state-modes 'ag-mode)
     (evil-add-hjkl-bindings ag-mode-map 'motion)))
```

leads to

```
ag.el:592:35:Error: Cannot open load file: no such file or directory, evil-core
```

**Comment by Wilfred** [comment]
OK, I've opened a merge request on the gitorious site: https://gitorious.org/evil/evil/merge_requests/75 . Evil also seems to be hosted on bitbucket: https://bitbucket.org/lyro/evil/wiki/Home but there are far more merged changes on the gitorious repo.

**Comment by lunaryorn** [comment]
@Wilfred Funny.  I thought Gitorious was long dead…
