### ISSUE TITLE
ag-dired can't work on win7 32bit

### ISSUE THREAD

**Issue by zijianyue** [Wilfred/ag.el#87]
I ag-dired tm_in.h in a directory ,but I got the error as below(I use msys environment, emacs 24.5):

  ag --nocolor -g 'tm_in.h' "a directory" | grep -v '^$' | sed s/\'/\\\'/ | xargs -I '{}' ls -alh '{}' &
  sed: -e expression #1,        char 8: unterminated `s' command

  ag finished at Tue Apr 28 14:35:44

**Comment by PythonNut** [comment]
I'm pretty sure this has to do with the way quoting works on Windows machines. 

See the following:

```
C:\> echo a
a
C:\> echo 'a'
a
C:\> echo \'a\'
a
C:\> REM yes, Windows is insane and uses ^ to escape.
C:\> echo ^'a^'
'a'
```

[this](https://github.com/Wilfred/ag.el/blob/9f0c3a70035d48738569d1095f53686e772c1dd2/ag.el#L469) is the line that the problem originates from. You ably fix it by branching on the value of `system-type`.

**Comment by zijianyue** [comment]
Thanks, but I'm still not very clear how to fix this .You mean error exist in this command :
" | grep -v '^$' | sed s/\\'/\\\\\\\\\\'/ | xargs -I '{}' ls "
How to write it on windows, please give a demonstrate.

**Comment by PythonNut** [comment]
This is a bug in the package itself. The author should decide what to do with it. I don't have Emacs on Windows, so I can't make a PR, unfortunately.

**Comment by Wilfred** [comment]
I'm afraid I don't have a Windows environment to test this on, right now.. Pull requests are certainly welcome in the mean time.
