### ISSUE TITLE
command not found: ag

### ISSUE THREAD

**Issue by lethjakman** [Wilfred/ag.el#93]
Hey, I've installed your plugin however every time I try to run it I get the error "zsh:1: command not found: ag" however ag is properly configured and works everywhere else on the machine.

**Comment by Wilfred** [comment]
Does the Emacs variable `exec-shell` match your `$PATH`? If not, you might find https://github.com/purcell/exec-path-from-shell helps.

**Comment by lethjakman** [comment]
I don't have an exec-shell, however I have an exec-path that matches my shell's $PATH. The odd thing is that I can run ag from C-!.

**Comment by Wilfred** [comment]
Weird. Can you run ag from eshell? What value does `exec-path` have? Where is ag installed?

Also, could you please provide a full traceback? `M-x toggle-debug-on-error`.

**Comment by Wilfred** [comment]
This isn't enough information for me to debug I'm afraid. Happy to reopen if you can answer my questions.

**Comment by speedenator** [comment]
I know this is closed, but for lethjakman --- I just fixed this problem. Turns out (on mac) when emacs is launched from the bar, it doesn't include /usr/local/bin. To fix:

    (setenv "PATH" (concat (getenv "PATH") ":/usr/local/bin"))

Note, you need that in addition to exec-path.
