### ISSUE TITLE
Handle very long ag commands better

### ISSUE THREAD

**Issue by mkaschenko** [Wilfred/ag.el#99]
Guys, I'd like to have this possibility because when I'm using it with 'projectile' the output is noisy.
Please take a loot at https://github.com/bbatsov/projectile/issues/897.

Or are there better ways to solve this problem?

**Comment by Wilfred** [comment]
It's certainly worth considering for 1.0.

In the meantime, why not just use `M-x toggle-truncate-lines`?

**Comment by mkaschenko** [comment]
Didn't think about `toggle-truncate-lines`. It's a nice solution. Thank you.

**Comment by Wilfred** [comment]
This will be fixed as part of v1.0, see screenshot below. It's currently on the `pretty_output_buffer_branch`. As a result, I'm going to close this.

![ag_v1](https://cloud.githubusercontent.com/assets/70800/11914390/e773726e-a677-11e5-8f80-801a7a130808.png)

**Comment by mkaschenko** [comment]
:+1:
